trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  versionMajor: 1
  versionMinor: 0
  TerraformVersion: '0.13.0'
  AzTerraformRegion: 'uksouth'
  AzTerraformResourceGroup: 'fm-geolocation-terraform'
  AzTerraformStorageAccount: 'fmgeolocationtfstate'
  AzSubscription: 'Personal-Pay-As-You-Go'

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: DotNetCoreCLI@2
      displayName: ".NET Core Restore"
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)/src/FM.GeoLocation.FuncApp/FM.GeoLocation.FuncApp.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: ".NET Core Build"
      inputs:
        command: 'build'
        projects: '$(Build.SourcesDirectory)/src/FM.GeoLocation.FuncApp/FM.GeoLocation.FuncApp.csproj'
        arguments: '-c Release'

    - task: CopyFiles@2
      displayName: 'Copy terraform folder into staging directory'
      inputs: 
        SourceFolder: '$(Build.sourcesDirectory)/terraform'
        Contents: '**'
        TargetFolder: '$(Build.artifactStagingDirectory)/terraform'

    - task: ArchiveFiles@2
      displayName: "Package FM.GeoLocation.FuncApp to artifact staging directory"
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/src/FM.GeoLocation.FuncApp/bin/Release/netcoreapp3.1/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/FM.GeoLocation.FuncApp.zip'
        replaceExistingArchive: true

    - task: DotNetCoreCLI@2
      displayName: "Pack FM.GeoLocation.Client"
      inputs:
        command: pack
        packagesToPack: '$(Build.SourcesDirectory)/src/FM.GeoLocation.Client/FM.GeoLocation.Client.csproj'
        packDestination: '$(Build.ArtifactStagingDirectory)'
        buildProperties: 'Version="$(versionMajor).$(versionMinor).$(Build.BuildId)"'

    - task: DotNetCoreCLI@2
      displayName: "Pack FM.GeoLocation.Contract"
      inputs:
        command: pack
        packagesToPack: '$(Build.SourcesDirectory)/src/FM.GeoLocation.Contract/FM.GeoLocation.Contract.csproj'
        packDestination: '$(Build.ArtifactStagingDirectory)'
        buildProperties: 'Version="$(versionMajor).$(versionMinor).$(Build.BuildId)"'

    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        publishVstsFeed: 'f6b61452-5280-47a1-b802-b2cfc8630b77/c57e8cd1-2aa2-4c0d-96cb-450405f73d4d'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    - publish: $(Build.artifactStagingDirectory)/FM.GeoLocation.FuncApp.zip
      displayName: Publish FM.GeoLocation.FuncApp artifact
      artifact: funcapp

    - publish: $(Build.artifactStagingDirectory)/terraform
      displayName: Publish terraform artifact
      artifact: terraform

- stage: pre_deploy
  jobs:
  - job: create_terraform_backend
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: none
      displayName: 'Skip checking out source'

    - task: AzureCLI@1
      displayName: 'Create terraform backend in Azure storage'
      inputs:
        azureSubscription: '$(AzSubscription)'
        scriptLocation: inlineScript
        inlineScript: |
          call az group create --location "$(AzTerraformRegion)" --name "$(AzTerraformResourceGroup)"
          call az storage account create --name "$(AzTerraformStorageAccount)" --resource-group "$(AzTerraformResourceGroup)" --location "$(AzTerraformRegion)" --sku "Standard_LRS"
          call az storage container create --name "terraform" --account-name "$(AzTerraformStorageAccount)"

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - template: deploy-application.yml
    parameters:
      environment: 'iris'