parameters:
- name: environment
  default: 'dev'

stages:
- stage: ${{ parameters.environment }}

  variables:
  - name: 'environment'
    value: ${{ parameters.environment }}

  jobs:
  - deployment: terraform_deploy

    pool:
      vmImage: 'ubuntu-latest'

    environment: 'fm-geolocation-${{ parameters.environment }}'

    strategy:
     runOnce:
       deploy:
        steps:
          - download: current
            displayName: 'Download terraform source artifact'
            artifact: terraform

          - task: AzureKeyVault@1
            inputs:
              azureSubscription: '$(AzSubscription)'
              keyVaultName: 'fm-geolocation-${{ parameters.environment }}'
              secretsFilter: '*'

          - task: TerraformInstaller@0
            displayName: 'Install terraform'
            inputs:
              terraformVersion: '$(TerraformVersion)'

          - task: TerraformTaskV1@0
            displayName: 'Terraform: azurerm init'
            inputs:
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              backendServiceArm: '$(AzSubscription)'
              backendAzureRmResourceGroupName: '$(AzTerraformResourceGroup)'
              backendAzureRmStorageAccountName: '$(AzTerraformStorageAccount)'
              backendAzureRmContainerName: terraform
              backendAzureRmKey: '${{ parameters.environment }}-terraform.tfstate'

          - task: TerraformTaskV1@0
            displayName: 'Terraform : azurerm plan'
            inputs:
              command: plan
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              commandOptions: '-var="environment=$(environment)"'
              environmentServiceNameAzureRM: '$(AzSubscription)'

          - task: TerraformTaskV1@0
            name: terraform_validate_and_apply
            displayName: 'Terraform : azurerm validate and apply'
            inputs:
              command: apply
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              commandOptions: '-var="environment=$(environment)"'
              environmentServiceNameAzureRM: '$(AzSubscription)'

          - powershell: |
              $terraformOutput = Get-Content "$(terraform_validate_and_apply.jsonOutputVariablesPath)" | ConvertFrom-Json
              $terraformOutput | Get-Member -MemberType NoteProperty | % { $o = $terraformOutput.($_.Name); Write-Host "##vso[task.setvariable variable=$($_.Name);isoutput=true;issecret=$($o.sensitive)]$($o.value)" }
            name: terraform_output
            displayName: 'Read terraform output vars'

  - deployment: 'funcapp_deploy'
    dependsOn: 'terraform_deploy'
    pool: 
      vmImage: 'windows-latest'

    environment: 'fm-geolocation-${{ parameters.environment }}'

    variables:
    - name: appdata_storage_connection
      value: $[ dependencies.terraform_deploy.outputs['terraform_deploy.terraform_output.appdata_storage_connection'] ]

    strategy:
     runOnce:
       deploy:
         steps:
          - download: current
            displayName: 'Download funcapp artifact'
            artifact: funcapp

          - task: AzureFunctionApp@1
            displayName: 'Azure Function App Deploy: FM-GeoLocation-FuncApp-$(Environment)'
            inputs:
              azureSubscription: '$(AzSubscription)'
              appType: functionAppLinux
              appName: 'geolocation-funcapp-$(environment)'
              deployToSlotOrASE: true
              resourceGroupName: 'FM-GeoLocation-$(environment)'
              package: '$(Pipeline.Workspace)/funcapp/FM.GeoLocation.FuncApp.zip'
              runtimeStack: 'DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0'
              AppSettings: '-Storage:TableStorageConnectionString "$(appdata_storage_connection)" -MaxMind:UserId "$(maxmind-userid)" -MaxMind:ApiKey "$(maxmind-apikey)"'